name: BuildChecks

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

env:
  CONAN_HOME: ${{ github.workspace }}/build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
      - name: Install poetry
        run: pipx install poetry
      - name: Prepare Environment
        run: |
          poetry install
          poetry run conan profile detect
      - name: Install Dependencies
        run: poetry run conan install . --build=missing -s build_type=Debug
      - name: Build
        run: |
          cmake --preset debug
          cmake --build --preset debug --target all
      - name: Run unittests
        run: ctest --preset debug
      - name: Check Tag Is New
        run: '[[ -z $(git tag -l | grep -E ^$(poetry run python scripts/get_project_version.py)$) ]]'
